# Generated by Django 5.1.2 on 2024-12-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookingtable_delete_assignmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='booking_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
