# Generated by Django 5.1.2 on 2024-12-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookingtable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Approved'), (2, 'Cancelled')], null=True),
        ),
    ]
