# Generated by Django 5.1.2 on 2024-12-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bookingtable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewdescription', models.TextField()),
                ('reviewrating', models.CharField(max_length=255)),
                ('movieid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movieshow')),
            ],
        ),
    ]
