# Generated by Django 5.1.2 on 2024-12-11 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewtable_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
