# Generated by Django 5.1.2 on 2024-12-11 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bookingtable_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='current_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
